### ISSUE TITLE
sh() commands that return error codes result in rake backtrace

### ISSUE THREAD

**Issue by coldnebo** [jimweirich/rake#45] opened 2011-06-02 14:56 UTC
Hi, sorry I didn't find the ticket system for this problem at first.  You can find the information on this issue here: https://gist.github.com/1003628

**Comment by jimweirich** [comment] 2011-06-05 23:44
Can't reproduce.  And the --trace flag works as intended.  I'm closing this.

**Closed as completed by jimweirich** 2011-06-05 23:44 UTC

**Comment by coldnebo** [comment] 2011-06-06 11:45
Ok, no prob.  Thanks for taking a look at it.
