### ISSUE TITLE
rake 0.9.2 case sensitive when reading database.yml

### ISSUE THREAD

**Issue by daveheitzman** [jimweirich/rake#62] opened 2011-07-25 15:46 UTC
I have had this problem on a couple of rails projects. I'm using ruby 1.8.7-334 and rake 0.9.2 came along with the last rails 3.0.9 point release. 

if I have a database.yml like this: 
development:
  adapter: mysql

then  "$ rake db:create"  produces 
=> rake aborted!
uninitialized constant Mysql

if I spell it like this: 
development:
  adapter: Mysql

it runs without error 

This started happening with rake 0.9.2 and has happened with 3 different rails apps, so I'm wondering if has started needing exact case strings ? 

thanks,

David

**Comment by jimweirich** [comment] 2011-07-25 16:20
There is nothing in Rake that deals with database yaml files.  I suspect the problem is with the rake tasks supplied by rails.  Can you verify?

**Comment by daveheitzman** [comment] 2011-07-25 16:50
I'll check into it. Thanks.

**Comment by daveheitzman** [comment] 2011-07-25 17:23
Indeed the trouble must be coming from within a gem, since a new rails project did not have the issue. Hopefully I can track down the gem that is at fault. 
Thanks,
Dave

**Comment by jimweirich** [comment] 2011-07-25 21:40
Great.  I'm going to close this issue.

**Closed as completed by jimweirich** 2011-07-25 21:40 UTC
