### ISSUE TITLE
Rake does not rebuild files that depend on deleted files

### ISSUE THREAD

**Issue by DavidEGrayson** [jimweirich/rake#286] opened 2014-07-28 22:07 UTC
The following Rakefile behaves in an undesirable way which is inconsistent with GNU Make:

``` ruby
file 'foo' => 'bar' do
  sh 'echo hi > foo'
end
file 'bar' do
  sh 'running bar task'
end
```

Suppose the file `foo` exists but `bar` has been deleted.  I would expect that since `bar` has been deleted, then `foo` would be considered out of date, and the Rake would run the `bar` task to attempt to rebuild `bar`, and then run the `foo` task to attempt to rebuild `foo`.  Instead, it only runs the `bar` task and then stops.

The expected output of the "rake" command is:

```
running bar task
echo hi > foo
```

The actual output of the "rake" command is:

```
running bar task
```

GNU Make behaves in the expected way.  If I use the following Makefile and run "make foo" while `foo` exists and `bar` does not exist, then I get the expected output from above.

``` Makefile
foo: bar
    echo hi > foo
bar:
    @echo running bar task
```

So clearly GNU Make and Rake are behaving differently, and I would argue that the GNU Make behavior is better.  If you are building a C or C++ program, then the GNU Make behavior in this situation is necessary to properly support the case where a header file has been deleted, and therefore all C files that previously depended on it need to be rebuilt.

It should be easy to fix this issue: we can just change https://github.com/jimweirich/rake/blob/master/lib/rake/file_task.rb#L24 to use `Rake::LATE` instead of `Rake::EARLY` (and we would need to add a definiton of `Rake::LATE` of course).  Does that sound good?  I would be happy to make a pull request if so.

I tried to look around to see if this issue has been reported before; I found issue #104 and [this forum post](https://www.ruby-forum.com/topic/58444) from 2006 but neither of them seem to directly address the issue of deleted files.

In case it matters, I am using Rake 10.1.0, JRuby 1.7.13, and Windows 8 64-bit.

**Comment by drbrain** [comment] 2014-07-28 22:44
Rake is intended to mimic the behavior of make, so this change sounds good.  A pull request would be excellent!

**Comment by damphyr** [comment] 2014-07-31 08:14
My initial reaction was that the header example was not a good reproduction of this behaviour and then I realized that I never explicitly define headers as dependencies, these are always generated fresh so the deleted files just vanish.

Having said that I would go as far as to say the original behaviour is a bug and _should_ be fixed on the following reasoning:
The dependency chain indicates a relationship to the action of all previous tasks. From rake's point of view if a file is missing then we cannot know what the file task for it does (recreates the file, tranforms it etc.) The only way to ensure consistency is to rerun the task and any tasks that depend on it. Every other state would be inconsistent.

So :+1:

**Comment by DavidEGrayson** [comment] 2014-07-31 16:35
Yeah, in my example Rakefile above, `bar` is analogous to a header file and the dependencies on `bar` were automatically generated as the result of previous builds.  When Rake runs, it should run the dummy `bar` task, then rebuild `foo`, at which point the record of foo's dependency on `bar` will be deleted from the dependency file, and the next time Rake runs it will know nothing about `bar`.

**Closed as completed** 2014-11-24 22:52 UTC
