### ISSUE TITLE
When a task inside a namespace depends on a task with the same name in the global namespace, false circular dependency results

### ISSUE THREAD

**Issue by FooBarWidget** [jimweirich/rake#274] opened 2014-05-05 17:21 UTC
Take a look at the following Rakefile:

```
task :foo do
  puts "foo"
end

task 'bar:foo' => :foo do
  puts "bar:foo"
end
```

Prior to Rake 10.2.0 (which introduced declaring tasks under a namespace using the 'x:y' syntax), running `rake bar:foo` prints:

```
foo
bar:foo
```

On the latest Rake, I get:

```
Circular dependency detected: TOP => bar:foo => bar:foo
```

Should this be considered an issue in Rake? If not, how should I fix my Rakefile?

**Comment by blackwinter** [comment] 2014-05-09 12:05
You can use the `rake` namespace to reference global tasks (cf. blackwinter/hen@df1dc31):

``` ruby
dependencies = ['rake:apache2', NATIVE_SUPPORT_TARGET].compact
```

**Comment by drbrain** [comment] 2014-05-13 23:09
As a workaround you can `task 'bar:foo' => '^foo'`

I'll see if I can fix this, it is a regression from 10.x behavior.

**Comment by drbrain** [comment] 2014-05-13 23:52
The problem here is when looking up prerequisites.

The scope of `task 'bar:foo'` is now "bar" so "foo" is no longer looked-up at top-level so a self-referential prerequisite is found.

Since `task 'bar:foo'` prior to 10.2.2 was undefined (there were no tests, not that this is a good indicator) I'm not sure if this is a regression anymore.

Since Jim merged this I'm going to leave this behavior as-is as there is a `'^foo'` workaround.

**Closed as completed by drbrain** 2014-05-13 23:52 UTC
Labels: type — bug, status — rejected

**Comment by FooBarWidget** [comment] 2014-05-14 08:22
Is the `^foo` syntax backward-compatible?

**Comment by drbrain** [comment] 2014-05-16 00:10
You run into a bug with 10.1.1 and earlier because `task 'bar:foo'` is undefined.

```
$ ruby -Ilib bin/rake --version
rake, version 10.1.1
$ ruby -Ilib bin/rake -f test.rf bar:foo
rake aborted!
undefined method `trim' for LL():Rake::Scope::EmptyScope

Tasks: TOP => bar:foo
(See full trace by running task with --trace)
```

For compatibility use `namespace` when dealing with old rake:

``` ruby
task 'foo' do puts "foo" end

namespace 'bar' do
  task 'foo' => '^foo' do puts "bar:foo" end
end
```
